version: '3.9'

services:
  app:
    container_name: "${APP_NAME}-backend"
    build: 
      context: .
      args:
        - DEV=true
    env_file: 
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    depends_on:
      - db

  
  db:
    image: postgres:13-alpine
    container_name: "${APP_NAME}-db"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


volumes:
  dev-db-data:
  dev-static-data: